image: map_tbmh.pgm
#image: rockin_day1_SLAM.pgm

# Resolution of the map, meters / pixel
resolution: 0.01
#resolution: 0.05

# The 2-D pose of the lower-left pixel in the map, as (x, y, yaw), with yaw as counterclockwise rotation (yaw=0 means no rotation).
origin: [-5.02, -4.02, 0]
#origin: [-17.525000, -17.525000, 0]

# Whether the white/black free/occupied semantics should be reversed (interpretation of thresholds is unaffected)
negate: 0

# Pixels with occupancy probability greater than this threshold are considered completely occupied.
occupied_thresh: 0.65

# Pixels with occupancy probability less than this threshold are considered completely free.
free_thresh: 0.196

